const canvas=document.getElementById("wheel"),ctx=canvas.getContext("2d"),spinButton=document.getElementById("spinButton"),spinButtonText=document.getElementById("spinButtonText"),resultModal=document.getElementById("resultModal"),resultIcon=document.getElementById("resultIcon"),resultEyebrow=document.getElementById("resultEyebrow"),resultTitle=document.getElementById("resultTitle"),resultPrize=document.getElementById("resultPrize"),resultMessage=document.getElementById("resultMessage"),modalActionButton=document.getElementById("modalActionButton"),confettiLayer=document.getElementById("confettiLayer");

// weight controla o peso relativo de cada resultado. Todos começam iguais.
const prizes=[
 {label:"Picolé",icon:"🍦",weight:1},
 {label:"Água mineral",icon:"💧",weight:1},
 {label:"Café",icon:"☕",weight:1},
 {label:"Suco",icon:"🧃",weight:1},
 {label:"Doce",icon:"🍬",weight:1},
 {label:"Tente mais uma vez",icon:"🔄",weight:1,retry:true}
];
const segmentColors=["#073B82","#12A978","#FFC515","#0B5FB7","#20B982","#F4B400"],textColors=["#fff","#fff","#173451","#fff","#fff","#173451"];
let rotation=0,spinning=false,retryAvailable=false;

function drawWheel(){const size=canvas.width,c=size/2,r=c-18,arc=Math.PI*2/prizes.length;ctx.clearRect(0,0,size,size);ctx.save();ctx.translate(c,c);ctx.beginPath();ctx.arc(0,0,r+8,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();for(let i=0;i<prizes.length;i++){const start=-Math.PI/2-arc/2+i*arc,end=start+arc,mid=start+arc/2;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,start,end);ctx.closePath();ctx.fillStyle=segmentColors[i];ctx.fill();ctx.strokeStyle="rgba(255,255,255,.92)";ctx.lineWidth=8;ctx.stroke();ctx.save();ctx.rotate(mid);ctx.translate(r*.60,0);ctx.rotate(Math.PI/2);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle=textColors[i];ctx.font='700 44px "Segoe UI Emoji","Apple Color Emoji",sans-serif';ctx.fillText(prizes[i].icon,0,-30);ctx.font='800 28px Inter,"Segoe UI",sans-serif';const words=prizes[i].label.split(" "),lines=[];let current="";for(const word of words){const test=current?`${current} ${word}`:word;if(ctx.measureText(test).width>178&&current){lines.push(current);current=word}else current=test}if(current)lines.push(current);const lh=31,sy=20-((lines.length-1)*lh)/2;lines.forEach((line,j)=>ctx.fillText(line,0,sy+j*lh));ctx.restore()}ctx.beginPath();ctx.arc(0,0,r*.16,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.restore()}
function pickPrizeIndex(){const total=prizes.reduce((s,p)=>s+p.weight,0);let roll=Math.random()*total;for(let i=0;i<prizes.length;i++){roll-=prizes[i].weight;if(roll<0)return i}return prizes.length-1}
function getTargetRotation(index){const seg=360/prizes.length,current=((rotation%360)+360)%360,target=(360-index*seg)%360;let delta=target-current;if(delta<0)delta+=360;const full=6+Math.floor(Math.random()*3);return rotation+full*360+delta}
function spinWheel(){if(spinning)return;spinning=true;retryAvailable=false;spinButton.disabled=true;spinButtonText.textContent="Girando...";const index=pickPrizeIndex(),prize=prizes[index],target=getTargetRotation(index),start=rotation,change=target-start,duration=4700,t0=performance.now();const ease=t=>1-Math.pow(1-t,5);function animate(now){const p=Math.min((now-t0)/duration,1);rotation=start+change*ease(p);canvas.style.transform=`rotate(${rotation}deg)`;if(p<1)return requestAnimationFrame(animate);rotation=target;canvas.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{spinning=false;prize.retry?showRetry(prize):showPrize(prize)},300)}requestAnimationFrame(animate)}
function openModal(){resultModal.hidden=false;document.body.style.overflow="hidden";modalActionButton.focus()}
function closeModal(){resultModal.hidden=true;document.body.style.overflow="";spinButton.disabled=false;spinButtonText.textContent=retryAvailable?"Girar novamente":"Girar roleta";spinButton.focus()}
function showPrize(prize){resultIcon.textContent=prize.icon;resultEyebrow.textContent="Parabéns!";resultTitle.textContent="Você ganhou";resultPrize.textContent=prize.label;resultMessage.textContent="Apresente esta tela ao atendente para resgatar seu prêmio.";modalActionButton.textContent="Entendi";retryAvailable=false;openModal();confetti()}
function showRetry(prize){resultIcon.textContent=prize.icon;resultEyebrow.textContent="Quase!";resultTitle.textContent="Você ganhou outra chance";resultPrize.textContent="Tente mais uma vez";resultMessage.textContent="Toque no botão abaixo para girar novamente.";modalActionButton.textContent="Girar novamente";retryAvailable=true;openModal()}
function confetti(){confettiLayer.innerHTML="";const colors=["#073B82","#12A978","#FFC515","#0B5FB7","#fff"];for(let i=0;i<72;i++){const p=document.createElement("span");p.className="confetti";p.style.left=`${Math.random()*100}%`;p.style.background=colors[i%colors.length];p.style.animationDuration=`${2.1+Math.random()*1.7}s`;p.style.animationDelay=`${Math.random()*.25}s`;p.style.setProperty("--x",`${-90+Math.random()*180}px`);p.style.setProperty("--r",`${180+Math.random()*540}deg`);confettiLayer.appendChild(p)}setTimeout(()=>confettiLayer.innerHTML="",4300)}
spinButton.addEventListener("click",spinWheel);document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeModal));modalActionButton.addEventListener("click",()=>{const retry=retryAvailable;closeModal();if(retry)setTimeout(()=>spinButton.click(),180)});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!resultModal.hidden)closeModal()});drawWheel();
